#!/usr/bin/env sh
# encoding: UTF-8

QUIRINUS_CXX="g++"
QUIRINUS_OPTIONS="-g -O3 -ansi -pedantic -Wno-long-long -static"
QUIRINUS_OPTIONS="${QUIRINUS_OPTIONS} -Ilib -Lbuild"
QUIRINUS_OPTIONS="${QUIRINUS_OPTIONS} -I/usr/local/include -L/usr/local/lib"
QUIRINUS_OPTIONS="${QUIRINUS_OPTIONS} -I/usr/include -L/usr/lib"


echo $QUIRINUS_OPTIONS


echo "quirinus::core"
${QUIRINUS_CXX} \
  -Wall ${QUIRINUS_OPTIONS} \
  -c "src/quirinus/core.cpp" -o "build/core.o"


echo "quirinus::codecs"
${QUIRINUS_CXX} \
  -Wall ${QUIRINUS_OPTIONS} \
  -c "src/quirinus/codecs.cpp" -o "build/codecs.o"


echo "quirinus::filesystem"
${QUIRINUS_CXX} \
  -Wall ${QUIRINUS_OPTIONS} \
  -c "src/quirinus/filesystem.cpp" -o "build/filesystem.o"


${QUIRINUS_CXX} \
  -Wall ${QUIRINUS_OPTIONS} \
  "build/core.o" \
  "build/codecs.o" \
  "build/filesystem.o" \
  "main.cpp" -o "main" \
  -lmpfr -lgmp -lpcre

